version: 2

project_name: codexa

builds:
  - main: ./cmd/codexa
    binary: codexa
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - formats: [tar.gz]
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      mtime: "{{ .CommitTimestamp }}"
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

checksum:
  name_template: checksums.txt

release:
  github:
    owner: aboubakary833
    name: codexa
